<?php
namespace Dedemao\Payjs\Actions;

use Dcat\Admin\Form;
use Dcat\Admin\Grid\RowAction;

class Refund extends RowAction
{
    protected static $resolvedWindow;

    /**
     * @return array|null|string
     */
    public function title()
    {
        return '<i class="feather icon-refresh-ccw"></i> 退款';
    }

    public function render()
    {
        if (! static::$resolvedWindow) {
            static::$resolvedWindow = true;

            [$width, $height] = $this->parent->option('dialog_form_area');

            Form::dialog('退款')
                ->click(".{$this->getElementClass()}")
                ->dimensions($width, $height)
                ->forceRefresh()
                ->success('Dcat.reload()');
        }

        $this->setHtmlAttribute([
            'data-url' => "{$this->resource()}/refund?id=".$this->getKey(),
        ]);

        return parent::render(); // TODO: Change the autogenerated stub
    }
}
